Repository openfun/warren, pull requests merged in 2023-08, with the labels that each got.

#47 🐛(api) return a count of 0 if there were no events
  CHANGELOG.md
  src/api/core/warren/models.py
  src/api/plugins/video/tests/test_api.py
  src/api/plugins/video/warren_video/indicators.py
Labels: bug

#49 ♻️(api) factorize video's indicators
  CHANGELOG.md
  src/api/core/warren/base_indicator.py
  src/api/core/warren/tests/test_base_indicator.py
  src/api/plugins/video/warren_video/api.py
  src/api/plugins/video/warren_video/indicators.py
Labels: improvement

#66 🩹(renovate) prefix ignored dev dependencies with `dev/`
  renovate.json
Labels: bug

#70 📌(frontend) pin all dependencies being used to ensure certainty and clear visibility
  src/frontend/apps/web/package.json
  src/frontend/package.json
  src/frontend/packages/ui/package.json
  src/frontend/yarn.lock
Labels: improvement, easy pick, dependencies

#72 🩹(api) fix client error handling with HttpException
  src/api/core/warren/models.py
  src/api/plugins/video/tests/test_api.py
  src/api/plugins/video/warren_video/api.py
  src/frontend/packages/ui/video/api/getVideoViews.ts
Labels: improvement

#71 ✨(app) enable consumer access to LTI Provider Configurations
  src/app/apps/lti/templates/config.xml
  src/app/apps/lti/urls.py
  src/app/apps/lti/views.py
  src/app/warren/settings.py
Labels: feature

#56 👷(circle) add backend images build and publication
  .circleci/config.yml
Labels: improvement, needs review

#78 👷(ci) harmonize CI linting rules with local development guidelines
  .circleci/config.yml
  src/api/core/pyproject.toml
  src/app/pyproject.toml
Labels: easy pick
