Repository openfun/warren, pull requests merged in 2023-11, with the labels that each got.

#129 📝(project) update README.md
  README.md
Labels: improvement

#103 📦️(app) bundle the frontend app build in the staticfiles
  .circleci/config.yml
  .gitignore
  Makefile
  src/app/Dockerfile
  src/app/apps/lti/templates/base.html
  src/app/staticfiles/.keep
  src/frontend/apps/web/vite.config.ts
Labels: improvement, needs review

#133 🐛(api) fix views computation
  src/api/plugins/video/tests/test_api.py
  src/api/plugins/video/warren_video/indicators.py
Labels: bug, needs review, easy pick

#125 ✨(frontend) enhance user experience with condensed metrics
  src/frontend/packages/ui/components/Autogrid/_index.scss
  src/frontend/packages/ui/components/Card/index.tsx
  src/frontend/packages/ui/components/Comparison/_index.scss
  src/frontend/packages/ui/components/Comparison/index.tsx
  src/frontend/packages/ui/components/Layout/Autogrid/_index.scss
  src/frontend/packages/ui/components/Layout/Autogrid/index.tsx
  src/frontend/packages/ui/components/Layout/Flexgrid/_index.scss
  src/frontend/packages/ui/components/Layout/Flexgrid/index.tsx
  src/frontend/packages/ui/components/Layout/_index.scss
  src/frontend/packages/ui/components/Metrics/_index.scss
  src/frontend/packages/ui/components/Metrics/index.tsx
  src/frontend/packages/ui/components/Tooltip/_index.scss
  src/frontend/packages/ui/index.scss
  src/frontend/packages/ui/video/api/getVideoViews.ts
  src/frontend/packages/ui/video/components/Datagrid/_index.scss
  src/frontend/packages/ui/video/components/Datagrid/index.tsx
  src/frontend/packages/ui/video/components/Filters/index.tsx
  src/frontend/packages/ui/video/components/Metrics/CompleteViewers.tsx
  src/frontend/packages/ui/video/components/Metrics/CompleteViews.tsx
  src/frontend/packages/ui/video/components/Metrics/TotalViewers.tsx
  src/frontend/packages/ui/video/components/Metrics/TotalViews.tsx
  src/frontend/packages/ui/video/components/Metrics/ViewsMetric.tsx
  src/frontend/packages/ui/video/components/Metrics/index.tsx
  src/frontend/packages/ui/video/components/Views/_index.scss
  src/frontend/packages/ui/video/components/Views/index.tsx
  src/frontend/packages/ui/video/contexts/filtersContext.tsx
  src/frontend/packages/ui/video/pages/Overview/index.tsx
Labels: needs review, feature

#139 Fix CI Hub job
  .circleci/config.yml
Labels: bug, FUN

#140 ➕(app) add whitenoise to serve static files
  src/app/apps/lti/tests/test_lti_config.py
  src/app/apps/lti/tests/test_lti_request.py
  src/app/apps/lti/tests/test_lti_select.py
  src/app/pyproject.toml
  src/app/warren/settings.py
Labels: needs review, feature

#142 🐛(indicators) fix method inheritance order for views indicators
  src/api/plugins/video/tests/test_api.py
  src/api/plugins/video/tests/test_indicators.py
  src/api/plugins/video/warren_video/indicators.py
Labels: bug, needs review

#141 🚑️(frontend) configure API and APP root urls in production
  .env.dist
  src/app/apps/lti/templates/base.html
  src/app/apps/lti/views.py
  src/app/warren/settings.py
  src/frontend/packages/ui/libs/axios.ts
Labels: critical, bug, needs review

#138 🔧(project) ignore `tests` subfolders for coverage measurement
  src/api/core/pyproject.toml
  src/app/pyproject.toml
Labels: improvement, needs review, easy pick

#144 ✨(api) add health check endpoints
  src/api/core/warren/api/__init__.py
  src/api/core/warren/api/health.py
  src/api/core/warren/db.py
  src/api/core/warren/tests/test_api_health.py
  src/api/core/warren/tests/test_db.py
Labels: needs review, feature

#147 ♻️(api) reorganize test files to follow package's organization
  src/api/core/warren/tests/api/__init__.py
  src/api/core/warren/tests/api/test_health.py
  src/api/core/warren/tests/indicators/__init__.py
  src/api/core/warren/tests/indicators/test_base.py
  src/api/core/warren/tests/indicators/test_mixins.py
  src/api/core/warren/tests/indicators/test_models.py
Labels: improvement, needs review

#148 🩹(api) redefine API logging configuration
  docker-compose.yml
  src/api/Dockerfile
  src/api/core/logging-config.dev.yaml
  src/api/core/logging-config.prod.yaml
Labels: bug

#150 🚑️(frontend) fix static files serving
  src/app/warren/settings.py
  src/frontend/apps/web/vite.config.ts
Labels: critical, bug
