Repository openfun/warren, pull requests merged in 2023-12, with the labels that each got.

#162 ⏪️(project) downgrade Python release for development stack
  src/api/Dockerfile
  src/app/Dockerfile
Labels: needs review, easy pick

#161 🐛(api) force single database engine and session per thread
  src/api/core/warren/api/__init__.py
  src/api/core/warren/db.py
  src/api/core/warren/indicators/mixins.py
Labels: bug

#135 Add k8s helm chart
  .env.dist
  .gitignore
  src/helm/CHANGELOG.md
  src/helm/README.md
  src/helm/charts/ralph/values.yaml
  src/helm/development.yaml
  src/helm/manifests/data-lake.yml
  src/helm/manifests/warren-secrets.yaml
  src/helm/warren/.helmignore
  src/helm/warren/Chart.lock
  src/helm/warren/Chart.yaml
  src/helm/warren/charts/api/.helmignore
  src/helm/warren/charts/api/Chart.yaml
  src/helm/warren/charts/api/templates/NOTES.txt
  src/helm/warren/charts/api/templates/_helpers.tpl
  src/helm/warren/charts/api/templates/cm_logging.yaml
  src/helm/warren/charts/api/templates/deployment.yaml
  src/helm/warren/charts/api/templates/hpa.yaml
  src/helm/warren/charts/api/templates/ingress.yaml
  src/helm/warren/charts/api/templates/job_db_migrate.yaml
  src/helm/warren/charts/api/templates/service.yaml
  src/helm/warren/charts/api/templates/tests/test-connection.yaml
  src/helm/warren/charts/api/values.yaml
  src/helm/warren/charts/app/.helmignore
  src/helm/warren/charts/app/Chart.yaml
  src/helm/warren/charts/app/templates/NOTES.txt
  src/helm/warren/charts/app/templates/_helpers.tpl
  src/helm/warren/charts/app/templates/deployment.yaml
  src/helm/warren/charts/app/templates/hpa.yaml
  src/helm/warren/charts/app/templates/ingress.yaml
  src/helm/warren/charts/app/templates/job_collect_static.yaml
  src/helm/warren/charts/app/templates/job_db_migrate.yaml
  src/helm/warren/charts/app/templates/pvc.yaml
  src/helm/warren/charts/app/templates/service.yaml
  src/helm/warren/charts/app/templates/tests/test-connection.yaml
  src/helm/warren/charts/app/values.yaml
  src/helm/warren/values.yaml
Labels: needs review, feature

#164 🥅(api) scope try-except block for Experience or Relation Creation
  src/api/core/warren/xi/routers/experiences.py
  src/api/core/warren/xi/routers/relations.py
Labels: improvement

#155 🚧(api) seed the experience index on bootstrap
  Makefile
  bin/seed_experience_index.py
  docker-compose.yml
Labels: feature

#171 ➖(api) remove unused factory-boy and faker
  src/api/core/pyproject.toml
Labels: needs review, FUN, dependencies

#175 🐛(api) fix seeding the Experience Index
  bin/seed_experience_index.py
Labels: bug

#173 🚀(api) remove useless sources from docker images
  src/api/Dockerfile
Labels: improvement, needs review

#170 🔧(api) configure FastAPI integration for sentry
  .env.dist
  src/api/core/warren/api/__init__.py
  src/api/core/warren/conf.py
Labels: needs review, feature

#176 🐛(api) fix docker development image
  src/api/Dockerfile
Labels: bug, needs review

#178 🐛(api) fix XI seeding script
  bin/seed_experience_index.py
Labels: bug, needs review

#177 🐛(api) fix warren command line parser
  src/api/core/warren/commands.py
  src/api/core/warren/tests/test_commands.py
Labels: bug, needs review

#179 📦️(frontend) integrate changesets to publish npm packages
  docker-compose.yml
  src/frontend/.changeset/README.md
  src/frontend/.changeset/config.json
  src/frontend/Dockerfile
  src/frontend/package.json
  src/frontend/yarn.lock
Labels: needs review, feature
