Repository openfun/warren, pull requests merged in 2023-06, with the labels that each got.

#10 🏗️ (project) add Ralph LRS to the development stack
  .circleci/config.yml
  .env.dist
  .gitignore
  Makefile
  docker-compose.yml
Labels: feature

#19 🔧(project) remove python-dev from backend Docker image
  src/backend/Dockerfile
Labels: needs review

#16 🐛(api) make custom pydantic types Date and Datetime compatible with JSON schema
  src/backend/core/warren/fields.py
Labels: bug

#12 ✨(backend) Add the LRS synchronous http backend
  .circleci/config.yml
  .env.dist
  CHANGELOG.md
  bin/pytest
  docker-compose.yml
  src/backend/.pylintrc
  src/backend/core/pyproject.toml
  src/backend/core/warren/api/__init__.py
  src/backend/core/warren/api/v1/__init__.py
  src/backend/core/warren/backends.py
  src/backend/core/warren/conf.py
  src/backend/core/warren/factories/base.py
  src/backend/core/warren/tests/conftest.py
  src/backend/core/warren/tests/fixtures/backends.py
  src/backend/plugins/video/__init__.py
  src/backend/plugins/video/tests/conftest.py
  src/backend/plugins/video/tests/test_api.py
  src/backend/plugins/video/warren_video/__init__.py
  src/backend/plugins/video/warren_video/api.py
  src/backend/plugins/video/warren_video/conf.py
  src/backend/plugins/video/warren_video/factories.py
Labels: feature

#18 ✨(project) add notebook service
  CHANGELOG.md
  Makefile
  bin/jupytext
  docker-compose.yml
  docs/notebook.md
  notebook/Dockerfile
  notebook/notebooks/benchmark_aggregation.md
Labels: needs review, feature

#27 👷(backend) Use astral-sh/ruff to make linting faster and simpler
  .circleci/config.yml
  Makefile
  src/backend/.pylintrc
  src/backend/core/pyproject.toml
  src/backend/core/warren/tests/__init__.py
  src/backend/core/warren/tests/fixtures/__init__.py
  src/backend/core/warren/tests/test_filters.py
  src/backend/plugins/video/tests/__init__.py
  src/backend/plugins/video/tests/conftest.py
  src/backend/plugins/video/tests/test_api.py
  src/backend/plugins/video/warren_video/api.py
  src/backend/plugins/video/warren_video/factories.py
Labels: improvement

#29 ✨(backend) Implement video views indicator
  src/backend/core/warren/base_indicator.py
  src/backend/core/warren/models.py
  src/backend/plugins/video/tests/test_api.py
  src/backend/plugins/video/warren_video/api.py
  src/backend/plugins/video/warren_video/indicators.py
  src/backend/plugins/video/warren_video/indicators/__init__.py
  src/backend/plugins/video/warren_video/models.py
Labels: needs review, feature
