Repository openfun/warren, pull requests merged in 2023-09, with the labels that each got.

#87 🥅 (api) catch BackendException from the LRS client
  src/api/core/warren/exceptions.py
  src/api/plugins/video/warren_video/api.py
  src/api/plugins/video/warren_video/indicators.py
Labels: bug

#85 ♻️(api) refactor indicators preprocessing
  src/api/core/warren/indicators/__init__.py
  src/api/core/warren/indicators/base.py
  src/api/core/warren/models.py
  src/api/core/warren/tests/test_base_indicator.py
  src/api/core/warren/tests/test_indicators_base.py
  src/api/core/warren/tests/test_utils.py
  src/api/core/warren/tests/test_xapi.py
  src/api/core/warren/utils.py
  src/api/core/warren/xapi.py
  src/api/plugins/video/warren_video/api.py
  src/api/plugins/video/warren_video/indicators.py
Labels: improvement, needs review

#96 🎨(api) import FastAPI HTTP status constants to avoid hardcoding integer values
  src/api/core/warren/filters.py
  src/api/plugins/video/warren_video/api.py
Labels: improvement

#94 🛂(app) limit deep-linking access to 'read-write-configure' LTI role
  src/app/apps/lti/tests/test_lti_select.py
  src/app/apps/lti/views.py
Labels: improvement

#98 Add generic indicator persistence
  .circleci/config.yml
  .env.dist
  Makefile
  bin/alembic
  bin/compose
  bin/pytest
  docker-compose.yml
  src/api/core/alembic.ini
  src/api/core/pyproject.toml
  src/api/core/warren/conf.py
  src/api/core/warren/indicators/base.py
  src/api/core/warren/indicators/mixins.py
  src/api/core/warren/indicators/models.py
  src/api/core/warren/migrations/env.py
  src/api/core/warren/migrations/versions/2aaa9e8fc591_update_cache_schema.py
  src/api/core/warren/migrations/versions/58a5b4238bbc_rename_cache_table.py
  src/api/core/warren/tests/conftest.py
  src/api/core/warren/tests/fixtures/db.py
  src/api/core/warren/tests/test_indicators_mixins.py
  src/api/core/warren/tests/test_indicators_models.py
Labels: feature

#100 👷(circle) move to a single docker image name
  .circleci/config.yml
  Makefile
  docker-compose.yml
  src/api/Dockerfile
Labels: improvement
