Repository openfun/warren, pull requests merged in 2023-07, with the labels that each got.

#35 ✨️(backend) add 2 endpoint parameters
  src/backend/core/warren/base_indicator.py
  src/backend/core/warren/conf.py
  src/backend/core/warren/models.py
  src/backend/plugins/video/tests/test_api.py
  src/backend/plugins/video/warren_video/api.py
  src/backend/plugins/video/warren_video/indicators.py
  src/backend/plugins/video/warren_video/models.py
Labels: feature

#36 (backend) Add base indicator tests
  src/backend/core/warren/factories/base.py
  src/backend/core/warren/tests/test_base_indicator.py
Labels: needs review

#39 Rename the API directory to a more descriptive name.
  .circleci/config.yml
  .env.dist
  CHANGELOG.md
  Makefile
  README.md
  docker-compose.yml
  src/api/.dockerignore
  src/api/Dockerfile
  src/api/core/LICENSE.md
  src/api/core/README.md
  src/api/core/logging-config.yaml
  src/api/core/pyproject.toml
  src/api/core/warren/__init__.py
  src/api/core/warren/api/__init__.py
  src/api/core/warren/api/v1/__init__.py
  src/api/core/warren/backends.py
  src/api/core/warren/base_indicator.py
  src/api/core/warren/conf.py
  src/api/core/warren/factories/__init__.py
  src/api/core/warren/factories/base.py
  src/api/core/warren/fields.py
  src/api/core/warren/filters.py
  src/api/core/warren/models.py
  src/api/core/warren/tests/__init__.py
  src/api/core/warren/tests/conftest.py
  src/api/core/warren/tests/fixtures/__init__.py
  src/api/core/warren/tests/fixtures/app.py
  src/api/core/warren/tests/fixtures/asynchronous.py
  src/api/core/warren/tests/test_base_indicator.py
  src/api/core/warren/tests/test_fields.py
  src/api/core/warren/tests/test_filters.py
  src/api/plugins/video/__init__.py
  src/api/plugins/video/pyproject.toml
  src/api/plugins/video/tests/__init__.py
  src/api/plugins/video/tests/conftest.py
  src/api/plugins/video/tests/test_api.py
  src/api/plugins/video/warren_video/__init__.py
  src/api/plugins/video/warren_video/api.py
  src/api/plugins/video/warren_video/conf.py
  src/api/plugins/video/warren_video/factories.py
  src/api/plugins/video/warren_video/indicators.py
  src/api/plugins/video/warren_video/models.py
Labels: critical, improvement

#41 🩹(api) revamp the neglected backend within `bin/pytest`
  bin/pytest
Labels: bug

#42 🩹(api) pin Ralph docker image
  docker-compose.yml
Labels: bug

#38 ✅(backend) add unique views indicator test
  src/api/plugins/video/tests/test_api.py
Labels: improvement, needs review

#45 🩹(project) ensure the pre-commit hook runs only on staged diffs
  bin/git-hook-pre-commit
Labels: improvement

#48 ♻️(api) rename video uuid to match xAPI semantic
  CHANGELOG.md
  src/api/plugins/video/tests/test_api.py
  src/api/plugins/video/warren_video/api.py
  src/api/plugins/video/warren_video/indicators.py
Labels: improvement

#50 ♻️(api) use concise names in indicators and models
  CHANGELOG.md
  src/api/core/warren/models.py
  src/api/plugins/video/tests/test_api.py
  src/api/plugins/video/warren_video/indicators.py
  src/frontend/packages/ui/video/Views.tsx
  src/frontend/packages/ui/video/types/index.ts
Labels: improvement

#52 🔧(project) activate renovate dashboard
  renovate.json
Labels: needs review, easy pick
