Repository openfun/warren, pull requests merged in 2024-02, with the labels that each got.

#206 💚(circle) change deprecated ubuntu machines
  .circleci/config.yml
Labels: dependencies

#209 🐛(api) serialize complex models before saving them
  src/api/core/warren/indicators/mixins.py
  src/api/core/warren/tests/indicators/test_mixins.py
Labels: critical, bug

#211 ♻️(api) configure root path global variable for alembic configuration
  src/api/core/warren/conf.py
  src/api/core/warren/migrations/__init__.py
  src/api/core/warren/tests/fixtures/db.py
Labels: easy pick
