Repository openfun/warren, pull requests merged in 2024-03, with the labels that each got.

#218 🐛(frontend) add missing CSS files in packages
  src/frontend/packages/core/.eslintignore
  src/frontend/packages/core/package.json
  src/frontend/packages/core/tsup.config.ts
  src/frontend/packages/video/.eslintignore
  src/frontend/packages/video/package.json
  src/frontend/packages/video/tsup.config.ts
  src/frontend/yarn.lock
Labels: bug, needs review

#219 🔖(frontend:patch) bump core release to 0.1.1
  src/frontend/packages/core/CHANGELOG.md
  src/frontend/packages/core/package.json
  src/frontend/packages/video/CHANGELOG.md
  src/frontend/packages/video/package.json
Labels: needs review, FUN, release

#224 🔖(minor) prepare 0.1.0 distribution release
  CHANGELOG.md
Labels: release

#225 🔧(project) fix ruff linter warning
  src/api/core/pyproject.toml
  src/app/pyproject.toml
Labels: needs review, easy pick

#223 🔧(app) add global settings for LTI parameters
  .env.dist
  src/app/apps/development/views.py
  src/app/warren/settings.py
Labels: improvement, easy pick
