Repository openfun/warren, pull requests merged in 2024-05, with the labels that each got.

#243 🐛(front/packages) export types in build package
  src/frontend/.changeset/shaggy-cats-wait.md
  src/frontend/packages/core/package.json
  src/frontend/packages/video/package.json
Labels: bug

#244 🔖(frontend:patch) bump core release to 0.1.2
  src/frontend/.changeset/shaggy-cats-wait.md
  src/frontend/packages/core/CHANGELOG.md
  src/frontend/packages/core/package.json
  src/frontend/packages/video/CHANGELOG.md
  src/frontend/packages/video/package.json
Labels: FUN, release

#247 ✨(frontend) add an error boundary wrapper component
  src/frontend/.changeset/stupid-mice-clap.md
  src/frontend/packages/core/package.json
  src/frontend/packages/core/src/components/BoundaryScreenError/_index.scss
  src/frontend/packages/core/src/components/BoundaryScreenError/index.tsx
  src/frontend/packages/core/src/components/LTI/AppContentLoader/index.tsx
  src/frontend/packages/core/src/index.scss
Labels: improvement

#249 ✅(api) use test database in tests
  src/api/core/warren/migrations/__init__.py
  src/api/core/warren/migrations/env.py
  src/api/core/warren/tests/api/test_health.py
  src/api/core/warren/tests/fixtures/db.py
  src/api/core/warren/tests/test_db.py
Labels: improvement

#250 🔨(api) make migrations with warren cli
  Makefile
  bin/warren
Labels: needs review

#251 ✨(cli) add migration check command
  CHANGELOG.md
  src/api/core/warren/cli.py
  src/api/core/warren/migrations/__init__.py
  src/api/core/warren/tests/test_cli.py
Labels: needs review
